<?php
// 网站配置项
return [
    'MERCHANT_TYPE' => [
        "T1" => [
            "name" => "淘宝",
            "key" => "T1",
            "value" => 1,
            "sort" => 1,
            "groupName" => "",
            "desc" => "",
        ],
        "T2" => [
            "name" => "天猫",
            "key" => "T2",
            "value" => 2,
            "sort" => 2,
            "groupName" => "",
            "desc" => "",
        ],
        "T3" => [
            "name" => "拼多多",
            "key" => "T3",
            "value" => 3,
            "sort" => 3,
            "groupName" => "",
            "desc" => "",
        ],
    ],
    'EXPRESS_TYPE' => [
        "T1" => [
            "name" => "韵达",
            "ename" => "yunda",
            "key" => "T1",
            "value" => 1,
            "sort" => 1,
            "groupName" => "",
            "desc" => "",
        ],
        "T2" => [
            "name" => "邮政",
            "ename" => "youzheng",
            "key" => "T2",
            "value" => 2,
            "sort" => 2,
            "groupName" => "",
            "desc" => "",
        ],
        "T3" => [
            "name" => "极兔",
            "ename" => "jitu",
            "key" => "T3",
            "value" => 3,
            "sort" => 3,
            "groupName" => "",
            "desc" => "",
        ],
        "T4" => [
            "name" => "百世",
            "ename" => "baishi",
            "key" => "T4",
            "value" => 4,
            "sort" => 4,
            "groupName" => "",
            "desc" => "",
        ],
        "T5" => [
            "name" => "申通",
            "ename" => "shentong",
            "key" => "T5",
            "value" => 5,
            "sort" => 5,
            "groupName" => "",
            "desc" => "",
        ],
        "T6" => [
            "name" => "圆通",
            "ename" => "yuantong",
            "key" => "T6",
            "value" => 6,
            "sort" => 6,
            "groupName" => "",
            "desc" => "",
        ],
    ]
];
